FROM python:3.9
WORKDIR /app

COPY myblog/requirements.txt myblog/routes.py myblog/.flaskenv ./
RUN python -m pip install --upgrade pip
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:routes"]