FROM python:3.9
WORKDIR /app
COPY --from=build-step /app/build ./build

RUN mkdir ./api
COPY api/requirements.txt api/api.py api/.flaskenv ./
RUN python -m pip install --upgrade pip
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

ENTRYPOINT ["./gunicorn.sh"]